name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          - check.bash
          - check_fuse.bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model
        shell: bash
        run: |
          wget https://github.com/Hiroshiba/vv_core_inference/releases/download/0.0.3/model.zip
          unzip model.zip

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint
        shell: bash
        run: |
          ruff check

      - name: Run script
        shell: bash
        run: |
          bash ${{ matrix.script }}
